### ISSUE TITLE
Integrate ECS Fargate - Help

### ISSUE THREAD

**Issue by rajeevr2715** [tmobile/t-vault#191]
We are planning to integrate T-vault into AWS ECS Fargate(https://aws.amazon.com/fargate/). 
While integrating, we have noticed the current t-vault docker installation requires --privileged flag in docker run. 
> `docker run --privileged -it -p 443:443 -p 8200:8200  your_tvault_docker_image_id /bin/bash`

But in AWS Fargate this parameter is not supported. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

If we pass the --cap-add IPC_LOCK instead of --privileged in the docker run, then the container will be up, but this parameter also not supported in AWS Fargate.

The error which throws while spinning up the container in Fargate - 

>  /opt/tvault/hcorp/bin/vault: Operation not permitted

We tried to setup the SKIP_SETCAP environment variable in ECS task definition, but that is also failing in the `vault operator  unseal  $(getkey 1) >> $INSTLOG` with >  /opt/tvault/hcorp/bin/vault: Operation not permitted error.

Is it possible to run the container without --privileged or --cap-add IPC_LOCK ? or is it possible to avoid the "Operation not permitted" error by using SKIP_SETCAP environment variable or someother way.

Please help.

**Comment by flying1574** [comment]
I also want know how to fix the error,Do you fix it ?

**Comment by flying1574** [comment]
> We are planning to integrate T-vault into AWS ECS Fargate(https://aws.amazon.com/fargate/).
> While integrating, we have noticed the current t-vault docker installation requires --privileged flag in docker run.
> 
> > `docker run --privileged -it -p 443:443 -p 8200:8200  your_tvault_docker_image_id /bin/bash`
> 
> But in AWS Fargate this parameter is not supported. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html
> 
> If we pass the --cap-add IPC_LOCK instead of --privileged in the docker run, then the container will be up, but this parameter also not supported in AWS Fargate.
> 
> The error which throws while spinning up the container in Fargate -
> 
> > /opt/tvault/hcorp/bin/vault: Operation not permitted
> 
> We tried to setup the SKIP_SETCAP environment variable in ECS task definition, but that is also failing in the `vault operator unseal $(getkey 1) >> $INSTLOG` with > /opt/tvault/hcorp/bin/vault: Operation not permitted error.
> 
> Is it possible to run the container without --privileged or --cap-add IPC_LOCK ? or is it possible to avoid the "Operation not permitted" error by using SKIP_SETCAP environment variable or someother way.
> 
> Please help.

Hi,Do you fix the problem?
